### ISSUE TITLE
*** No rule to make target 'CHASD___12.dat', needed by 'CHASD___12.c'.  Stop.

### ISSUE THREAD

**Issue by Naresh-engineer** [RoelN/font-face-render-check#1]
hi 

```
      i would like to print some Chinese and Indian font . how to fix it .

   ubuntu@ubuntu-OptiPlex-360:~/Naresh/desktop/mcufont-master$ make
```

make -C encoder
make[1]: Entering directory '/home/ubuntu/Naresh/desktop/mcufont-master/encoder'
./unittests
Running cxxtest tests (5 tests).....OK!
make[1]: Leaving directory '/home/ubuntu/Naresh/desktop/mcufont-master/encoder'
make -C fonts
make[1]: Entering directory '/home/ubuntu/Naresh/desktop/mcufont-master/fonts'
make[1]: **\* No rule to make target 'CHASD___12.dat', needed by 'CHASD___12.c'.  Stop.
make[1]: Leaving directory '/home/ubuntu/Naresh/desktop/mcufont-master/fonts'
Makefile:2: recipe for target 'all' failed
make: **\* [all] Error 2

```
     i tried but i got this error . please let me know to fix this problem.
```

**Comment by RoelN** [comment]
Hi, I'm happy to help but I think you might be posting your question in the wrong repo. There's no `make` process for font-face-render-check. It works with a built-in font, so no need to add your own.
